# Generated by Django 4.1.3 on 2022-11-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_customuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.AddField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
