# Generated by Django 4.1.3 on 2022-12-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_remove_customuser_birthday_customuser_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
